version: "3.8"

services:
  uwsgi:
    build: ./uwsgi
    container_name: kiosk-uwsgi
    restart: always
    expose:
      - 5000
    volumes:
      - ./data:/kiosk/data
      - ./backup:/kiosk/backup

  nginx:
    build: ./nginx
    container_name: kiosk-nginx
    restart: always
    depends_on:
      - uwsgi
    ports:
      - 80:80
