version: "3.7"

volumes:
  data: kiosk_data
  backup: kiosk_backup

services:

  wsgi:
    build: ./wsgi
    container_name: kiosk-wsgi
    volumes:
      - kiosk_data:/data
      - kiosk_backup:/backup
    restart: always
    expose:
      - 5000

  nginx:
    build: ./nginx
    container_name: kiosk-nginx
    restart: always
    ports:
      - "80:80"