#! /bin/sh
### BEGIN INIT INFO
# Provides: kiosk
# Required-Start: $syslog
# Required-Stop: $syslog
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: Kiosk client
# Description:
### END INIT INFO
 
case "$1" in
    start)
        echo "Kiosk wird gestartet"
	chmod +x /home/pi/kiosk/startclient.sh
        # Starte Programm
        /home/pi/kiosk/startclient.sh &
        ;;
    stop)
        echo "Kiosk wird beendet"
        # Beende Programm
        killall python3
        ;;
    *)
        echo "User: /etc/init.d/kiosk {start|stop}"
        exit 1
        ;;
esac
 
exit 0
